#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

import wx
import gettext

from GenTestFrame import GenTestFrame


if __name__ == "__main__":
    gettext.install("GenTest") # replace with the appropriate catalog name

    GenTest = wx.PySimpleApp()
    gentestFrame = GenTestFrame(None, wx.ID_ANY, "")
    GenTest.SetTopWindow(gentestFrame)
    gentestFrame.Show()
    GenTest.MainLoop()
