#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Apr  3 19:41:20 2021
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from GenTestFrame import GenTestFrame


if __name__ == "__main__":
    gettext.install("GenTest") # replace with the appropriate catalog name

    GenTest = wx.PySimpleApp()
    gentestFrame = GenTestFrame(None, wx.ID_ANY, "")
    GenTest.SetTopWindow(gentestFrame)
    gentestFrame.Show()
    GenTest.MainLoop()
